[
  {
    name: "Nusrat Jahan",
    photoURL: "https://ibb.co.com/m5HyMBd",
    email: "nusrat.jahan@example.com",
    hsc: "Science",
    graduation: "B.Sc. in Textile Engineering",
    subject: "Textile Engineering",
    work: "Product Development Manager at a Fashion House",
    mentoringSubject: "Fashion Design and Textiles",
    fees: 3000,
    courseDetails:
      "Mentoring on textile materials, fashion design principles, and product development.",
    role: "mentor",
  },
  {
    name: "Fahmida Khan",
    photoURL: "https://i.ibb.co.com/N3SJ4hx/2149288938.jpg",
    email: "fahmida.khan@example.com",
    hsc: "Business Studies",
    graduation: "BBA in Human Resource Management",
    subject: "HR Management",
    work: "HR Manager at a multinational company",
    mentoringSubject: "Human Resource Management",
    fees: 2500,
    courseDetails:
      "Providing guidance on HR policies, recruitment strategies, and employee engagement.",
    role: "mentor",
  },
  {
    name: "Tahmina Akter",
    photoURL: "https://i.ibb.co.com/XLCXnQ0/2149429341.jpg",
    email: "tahmina.akter@example.com",
    hsc: "Commerce",
    graduation: "B.Com in Accounting",
    subject: "Accounting",
    work: "Chartered Accountant at a leading firm",
    mentoringSubject: "Accounting and Financial Management",
    fees: 4000,
    courseDetails:
      "Teaching fundamentals of accounting, auditing, and tax management.",
    role: "mentor",
  },
  {
    name: "Anika Rahman",
    photoURL: "https://i.ibb.co.com/6sWB883/2149122758.jpg",
    email: "anika.rahman@example.com",
    hsc: "Science",
    graduation: "B.Sc. in Civil Engineering",
    subject: "Civil Engineering",
    work: "Structural Engineer at a construction company",
    mentoringSubject: "Civil Engineering Fundamentals",
    fees: 3500,
    courseDetails:
      "Guiding on structural design, material properties, and project management.",
    role: "mentor",
  },
  {
    name: "Shakila Ahmed",
    photoURL: "https://i.ibb.co.com/Z8x3vsg/17801.jpg",
    email: "shakila.ahmed@example.com",
    hsc: "Science",
    graduation: "B.Sc. in Electrical Engineering",
    subject: "Electrical Engineering",
    work: "Project Engineer at an energy company",
    mentoringSubject: "Electrical Systems and Automation",
    fees: 3200,
    courseDetails:
      "Offering mentoring on electrical circuit design, power systems, and automation.",
    role: "mentor",
  },
  {
    name: "Maliha Islam",
    photoURL: "https://i.ibb.co.com/CJrnPBq/2150388820.jpg",
    email: "maliha.islam@example.com",
    hsc: "Science",
    graduation: "B.Sc. in Computer Science",
    subject: "Computer Science",
    work: "Software Developer at a tech startup",
    mentoringSubject: "Software Development and Engineering",
    fees: 3800,
    courseDetails:
      "Mentoring on coding practices, software design patterns, and project management.",
    role: "mentor",
  },
  {
    name: "Samia Chowdhury",
    photoURL: "https://example.com/photos/samia.jpg",
    email: "samia.chowdhury@example.com",
    hsc: "Arts",
    graduation: "B.A. in Fashion Design",
    subject: "Fashion Design",
    work: "Freelance Fashion Designer",
    mentoringSubject: "Fashion Design and Illustration",
    fees: 2700,
    courseDetails:
      "Teaching fashion sketching, digital design tools, and portfolio building.",
    role: "mentor",
  },
  {
    name: "Rubina Parvin",
    photoURL: "https://example.com/photos/rubina.jpg",
    email: "rubina.parvin@example.com",
    hsc: "Science",
    graduation: "B.Sc. in Mechanical Engineering",
    subject: "Mechanical Engineering",
    work: "Research Engineer at an automotive company",
    mentoringSubject: "Mechanical Design and Innovation",
    fees: 4200,
    courseDetails:
      "Guiding in mechanical design, manufacturing processes, and research methods.",
    role: "mentor",
  },
  {
    name: "Sadia Haque",
    photoURL: "https://example.com/photos/sadia.jpg",
    email: "sadia.haque@example.com",
    hsc: "Science",
    graduation: "B.Sc. in Chemical Engineering",
    subject: "Chemical Engineering",
    work: "Process Engineer at a pharmaceutical company",
    mentoringSubject: "Chemical Process Engineering",
    fees: 3100,
    courseDetails:
      "Mentoring on chemical process design, safety, and operations management.",
    role: "mentor",
  },
  {
    name: "Nadia Rahman",
    photoURL: "https://example.com/photos/nadia.jpg",
    email: "nadia.rahman@example.com",
    hsc: "Business Studies",
    graduation: "BBA in Finance",
    subject: "Finance",
    work: "Financial Analyst at a bank",
    mentoringSubject: "Finance and Investment Analysis",
    fees: 3700,
    courseDetails:
      "Teaching principles of investment, financial modeling, and market analysis.",
    role: "mentor",
  },

  {
    name: "Ayesha Rahman",
    photoURL: "https://randomuser.me/api/portraits/women/1.jpg",
    email: "ayesha.rahman@example.com",
    phone: "+8801712345671",
    graduation: "Dhaka University",
    subject: "Electrical Engineering",
    work: "Senior Engineer at Grameenphone",
    mentoringSubject: "Power Systems Engineering",
    fees: 2000,
    courseDetails:
      "Introduction to Electrical Power Systems, Power Generation, Transmission & Distribution, Power Flow Analysis, Fault Analysis, and Renewable Energy Integration.",
    role: "MENTOR",
  },
  {
    name: "Farzana Islam",
    photoURL: "https://randomuser.me/api/portraits/women/2.jpg",
    email: "farzana.islam@example.com",
    phone: "+8801712345672",
    graduation: "Bangladesh University of Engineering and Technology (BUET)",
    subject: "Civil Engineering",
    work: "Project Manager at BRAC",
    mentoringSubject: "Construction Project Management",
    fees: 2500,
    courseDetails:
      "Project Planning & Scheduling, Resource Management, Construction Site Management, Risk Management in Construction, and Sustainable Building Practices.",
    role: "MENTOR",
  },
  {
    name: "Rima Khatun",
    photoURL: "https://randomuser.me/api/portraits/women/3.jpg",
    email: "rima.khatun@example.com",
    phone: "+8801712345673",
    graduation: "Jahangirnagar University",
    subject: "Accounting",
    work: "Financial Analyst at Unilever Bangladesh",
    mentoringSubject: "Corporate Financial Accounting",
    fees: 1800,
    courseDetails:
      "Corporate Financial Statements, Budgeting and Forecasting, Financial Reporting, Auditing Standards, and Taxation in Bangladesh.",
    role: "MENTOR",
  },
  {
    name: "Nafisa Haque",
    photoURL: "https://randomuser.me/api/portraits/women/4.jpg",
    email: "nafisa.haque@example.com",
    phone: "+8801712345674",
    graduation: "North South University",
    subject: "Career Counseling",
    work: "Career Coach at Pathao",
    mentoringSubject: "Career Development and Personal Branding",
    fees: 1500,
    courseDetails:
      "Career Path Exploration, Resume Building, Cover Letter Writing, Job Interview Techniques, Personal Branding on LinkedIn, and Salary Negotiation.",
    role: "MENTOR",
  },
  {
    name: "Sabina Akter",
    photoURL: "https://randomuser.me/api/portraits/women/5.jpg",
    email: "sabina.akter@example.com",
    phone: "+8801712345675",
    graduation: "American International University-Bangladesh (AIUB)",
    subject: "Computer Science & Engineering",
    work: "Software Developer at Tiger IT",
    mentoringSubject: "Full-Stack Web Development",
    fees: 2200,
    courseDetails:
      "HTML, CSS, JavaScript, React for Frontend, Node.js for Backend, Database Management (SQL/NoSQL), REST APIs, and Deploying Web Applications.",
    role: "MENTOR",
  },
  {
    name: "Tasnim Jahan",
    photoURL: "https://randomuser.me/api/portraits/women/6.jpg",
    email: "tasnim.jahan@example.com",
    phone: "+8801712345676",
    graduation: "Khulna University of Engineering & Technology (KUET)",
    subject: "Mechanical Engineering",
    work: "Mechanical Engineer at BEXIMCO",
    mentoringSubject: "Mechanical Design and CAD",
    fees: 2300,
    courseDetails:
      "3D Modeling in CAD, Machine Design Principles, Material Selection, Structural Analysis, and Manufacturing Processes.",
    role: "MENTOR",
  },
];
